SOAL 1

In [23]:
nama = "Raynaldi Sandy"
kode_mahasiswa = "20210801453"
mata_kuliah = "Machine Learning"

print("Data Diri")
print("Nama : ", nama )
print("Kode_Mahasiswa : ", kode_mahasiswa )
print("Perkuliahan :", mata_kuliah)

Data Diri
Nama :  Raynaldi Sandy
Kode_Mahasiswa :  20210801453
Perkuliahan : Machine Learning


SOAL 2

In [24]:
matriksC = [(1,2,3), (4,5,6)]
print (matriksC)

[(1, 2, 3), (4, 5, 6)]


SOAL 3

In [25]:
matriks = [(2,2), (2,2), (2,2)]
print (matriks)

[(2, 2), (2, 2), (2, 2)]


SOAL 4

In [26]:
import numpy as np

SOAL 5

In [27]:
from numpy import *
matriks = range(32)
matriks = reshape(matriks, (4,8))
print(matriks)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]


SOAL 6

In [28]:
import numpy as np
from numpy import *

matriks = np.random.randint(1,5,(3,30))
print(matriks)

[[2 4 2 3 4 1 3 1 4 3 4 2 4 3 1 3 3 2 3 4 1 3 2 1 1 1 2 3 2 1]
 [2 2 2 4 2 1 2 4 4 2 4 1 3 1 4 4 2 3 3 2 4 4 3 4 2 4 2 4 2 4]
 [4 2 3 2 2 3 1 1 2 4 1 4 1 4 3 3 3 2 4 4 2 1 2 1 3 4 1 4 3 1]]
